In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('visawise.csv')
df.head()

Unnamed: 0  CASE_STATUS  FULL_TIME_POSITION  EMPLOYER_ACCEPTANCE_HA  \
0          18          1.0                   1                       0   
1          19          1.0                   1                       0   
2          22          1.0                   1                       0   
3          23          1.0                   1                       0   
4          25          1.0                   1                       0   

   EMPLOYER_ACCEPTANCE_LA  EMPLOYER_ACCEPTANCE_MA  EMPLOYER_ACCEPTANCE_VHA  \
0                       0                       0                        0   
1                       0                       0                        0   
2                       0                       0                        0   
3                       0                       0                        0   
4                       0                       0                        0   

   EMPLOYER_ACCEPTANCE_VLA  JOB_ACCEPTANCE_HA  JOB_ACCEPTANCE_LA  ...  \
0                        0                  0                  0  ...   
1                        0                  0                  0  ...   
2                        0                  0                  0  ...   
3                        0                  0                  0  ...   
4                        0                  0                  0  ...   

   ILLINOIS  MASSACHUSETTS  PENNSYLVANIA  FLORIDA  GEORGIA  WASHINGTON  \
0         0              0             0        0        0           0   
1         0              0             0        0        0           0   
2         0              0             0        0        0           0   
3         0              0             0        0        0           0   
4         0              0             0        0        0           0   

   VIRGINIA  MICHIGAN  NORTH CAROLINA  OHIO  
0         0         0               0     0  
1         1         0               0     0  
2         0         0               0     0  
3         0         0               0     0  
4         0         0               0     0  

[5 rows x 53 columns]

# Splitting the data into train test split

In [3]:
x = df.drop(['CASE_STATUS','Unnamed: 0'], axis=1) # Independent variables
y = df['CASE_STATUS'] # Dependent variables

In [4]:
print(x.columns.shape)
x.columns

(51,)


Index(['FULL_TIME_POSITION', 'EMPLOYER_ACCEPTANCE_HA',
       'EMPLOYER_ACCEPTANCE_LA', 'EMPLOYER_ACCEPTANCE_MA',
       'EMPLOYER_ACCEPTANCE_VHA', 'EMPLOYER_ACCEPTANCE_VLA',
       'JOB_ACCEPTANCE_HA', 'JOB_ACCEPTANCE_LA', 'JOB_ACCEPTANCE_MA',
       'JOB_ACCEPTANCE_VHA', 'JOB_ACCEPTANCE_VLA', 'SOC_ACCEPTANCE_HA',
       'SOC_ACCEPTANCE_LA', 'SOC_ACCEPTANCE_MA', 'SOC_ACCEPTANCE_VHA',
       'SOC_ACCEPTANCE_VLA', 'YEAR_2012.0', 'YEAR_2013.0', 'YEAR_2014.0',
       'YEAR_2015.0', 'YEAR_2016.0', 'WAGE_CATEGORY_LOW',
       'WAGE_CATEGORY_MEDIUM', 'WAGE_CATEGORY_VERY HIGH',
       'WAGE_CATEGORY_VERY LOW', 'JOB_Artist', 'JOB_Audit', 'JOB_Database',
       'JOB_Education', 'JOB_Engineer', 'JOB_Estate', 'JOB_Finance', 'JOB_It',
       'JOB_Manager', 'JOB_Medical', 'JOB_Pr', 'JOB_Scm', 'CALIFORNIA',
       'TEXAS', 'NEW YORK', 'NEW JERSEY', 'ILLINOIS', 'MASSACHUSETTS',
       'PENNSYLVANIA', 'FLORIDA', 'GEORGIA', 'WASHINGTON', 'VIRGINIA',
       'MICHIGAN', 'NORTH CAROLINA', 'OHIO'],
      d

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

X_train.fillna(0, inplace=True)
X_test.fillna(0, inplace=True)
y_train.fillna(0, inplace=True)
y_test.fillna(0, inplace=True)

C:\Anaconda3\lib\site-packages\pandas\core\frame.py:4317: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(


In [6]:
X_train

FULL_TIME_POSITION  EMPLOYER_ACCEPTANCE_HA  EMPLOYER_ACCEPTANCE_LA  \
118611                    1                       0                       0   
1303000                   1                       0                       0   
1051437                   1                       0                       0   
410149                    0                       0                       0   
1712576                   1                       0                       0   
...                     ...                     ...                     ...   
836489                    1                       0                       0   
491263                    1                       0                       0   
2568076                   1                       0                       0   
491755                    1                       0                       0   
128037                    0                       0                       0   

         EMPLOYER_ACCEPTANCE_MA  EMPLOYER_ACCEPTANCE_VHA  \
118611                        0                        0   
1303000                       0                        0   
1051437                       0                        0   
410149                        0                        1   
1712576                       0                        0   
...                         ...                      ...   
836489                        0                        1   
491263                        0                        0   
2568076                       0                        0   
491755                        0                        0   
128037                        0                        0   

         EMPLOYER_ACCEPTANCE_VLA  JOB_ACCEPTANCE_HA  JOB_ACCEPTANCE_LA  \
118611                         0                  0                  0   
1303000                        0                  0                  0   
1051437                        0                  0                  0   
410149                         0                  0                  0   
1712576                        0                  0                  0   
...                          ...                ...                ...   
836489                         0                  0                  0   
491263                         0                  0                  0   
2568076                        0                  0                  0   
491755                         0                  0                  0   
128037                         0                  0                  0   

         JOB_ACCEPTANCE_MA  JOB_ACCEPTANCE_VHA  ...  ILLINOIS  MASSACHUSETTS  \
118611                   0                   0  ...         0              0   
1303000                  0                   1  ...         0              0   
1051437                  0                   0  ...         0              0   
410149                   0                   0  ...         1              0   
1712576                  0                   0  ...         0              0   
...                    ...                 ...  ...       ...            ...   
836489                   0                   0  ...         0              0   
491263                   0                   0  ...         0              0   
2568076                  0                   1  ...         0              0   
491755                   0                   0  ...         0              0   
128037                   0                   1  ...         0              0   

         PENNSYLVANIA  FLORIDA  GEORGIA  WASHINGTON  VIRGINIA  MICHIGAN  \
118611              0        0        0           0         0         0   
1303000             0        0        0           0         0         0   
1051437             0        0        0           0         0         0   
410149              0        0        0           0         0         0   
1712576             0        0        0           0         0         0   
...               ...      ...      ...

# MODELS

# Nural Networks

In [7]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report
from sklearn import metrics

mlp = MLPClassifier(hidden_layer_sizes=(20,20,20,20,20), max_iter=1000)
mlp.fit(X_train, y_train)

y_pred_mlp = mlp.predict(X_test)
confusion = metrics.confusion_matrix(y_test, y_pred_mlp)
print(confusion)
print(metrics.classification_report(y_test, y_pred_mlp))

[[   227  18685]
 [    32 519860]]
              precision    recall  f1-score   support

         0.0       0.88      0.01      0.02     18912
         1.0       0.97      1.00      0.98    519892

    accuracy                           0.97    538804
   macro avg       0.92      0.51      0.50    538804
weighted avg       0.96      0.97      0.95    538804



In [8]:
print(metrics.recall_score(y_test, y_pred_mlp))
print(metrics.f1_score(y_test, y_pred_mlp))

0.9999384487547414
0.9823163778288174


In [14]:
x = [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
print(x, len(x))
prediction = mlp.predict([x])
print(prediction)

[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 51
[0.]


In [18]:
import pickle
# open a file, where you ant to store the data
file = open('nueral_netwoks.pkl', 'wb')

# dump information to that file
pickle.dump(mlp, file)

file.close() 

# Applying Logistic Regression Algorithm

In [21]:
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression


LogReg = LogisticRegression()
LogReg.fit(X_train, y_train)
y_pred = LogReg.predict(X_test)

print("test", y_test[:10])
print("pred", y_pred[:10])
print()

print(metrics.confusion_matrix(y_test,y_pred))
print(classification_report(y_test, y_pred))

C:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


test 1285464    1.0
2646597    1.0
1279586    1.0
1426548    1.0
76436      1.0
410927     1.0
843402     1.0
508583     1.0
1627361    1.0
2048489    1.0
Name: CASE_STATUS, dtype: float64
pred [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[    27  18885]
 [     8 519884]]
              precision    recall  f1-score   support

         0.0       0.77      0.00      0.00     18912
         1.0       0.96      1.00      0.98    519892

    accuracy                           0.96    538804
   macro avg       0.87      0.50      0.49    538804
weighted avg       0.96      0.96      0.95    538804



<br><br>
# Applying Decision Tree Classifier

In [22]:
from sklearn import tree

dtree = tree.DecisionTreeClassifier()
dtree = dtree.fit(X_train, y_train)

y_pred_dt = dtree.predict(X_test)


print("test", y_test[:10])
print("pred", y_pred[:10])
print()

print(dtree.score(X_test,y_test))
print(metrics.confusion_matrix(y_test,y_pred_dt))
print(metrics.classification_report(y_test, y_pred_dt))
#print(metrics.precision_score(y_test,y_pred))   # Parameter "average" is requred if not a binary model
#print(metrics.recall_score(y_test,y_pred))      # Parameter "average" is requred if not a binary model
#print(metrics.f1_score(y_test,y_pred))  

test 1285464    1.0
2646597    1.0
1279586    1.0
1426548    1.0
76436      1.0
410927     1.0
843402     1.0
508583     1.0
1627361    1.0
2048489    1.0
Name: CASE_STATUS, dtype: float64
pred [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

0.9650912019955309
[[   270  18642]
 [   167 519725]]
              precision    recall  f1-score   support

         0.0       0.62      0.01      0.03     18912
         1.0       0.97      1.00      0.98    519892

    accuracy                           0.97    538804
   macro avg       0.79      0.51      0.51    538804
weighted avg       0.95      0.97      0.95    538804



<br><br>
# Applying Random Forest Classifier

In [73]:
# from sklearn.ensemble import RandomForestClassifier
# rd =  RandomForestClassifier(n_estimators = 75 , random_state = 50)
# rd.fit(X_train,y_train)

# y_pred_rfs = rd.predict_proba(X_test)

print("test", y_test[:10])
print("pred", y_pred_rfs[:10])

print(metrics.confusion_matrix(y_test,pred))
print(metrics.classification_report(y_test, pred))
print(metrics.precision_score(y_test,pred))   # Parameter "average" is requred if not a binary model
print(metrics.recall_score(y_test,pred))
print(metrics.f1_score(y_test, pred))# Parameter "average" is requred if not a binary model

test 1285464    1.0
2646597    1.0
1279586    1.0
1426548    1.0
76436      1.0
410927     1.0
843402     1.0
508583     1.0
1627361    1.0
2048489    1.0
Name: CASE_STATUS, dtype: float64
pred [[0.00258843 0.99741157]
 [0.0426505  0.9573495 ]
 [0.01609128 0.98390872]
 [0.02264496 0.97735504]
 [0.00348062 0.99651938]
 [0.00348062 0.99651938]
 [0.01915826 0.98084174]
 [0.01654143 0.98345857]
 [0.05611203 0.94388797]
 [0.07162147 0.92837853]]
[[   244  18668]
 [   100 519792]]
              precision    recall  f1-score   support

         0.0       0.71      0.01      0.03     18912
         1.0       0.97      1.00      0.98    519892

    accuracy                           0.97    538804
   macro avg       0.84      0.51      0.50    538804
weighted avg       0.96      0.97      0.95    538804

0.9653307580878803
0.9998076523585668
0.9822667694680032


In [51]:
y_pred_rfs.shape

(538804, 2)

In [58]:
j=0
pred = np.zeros((538804,1))
for i in y_pred_rfs:
    pred[j] = np.argmax(i, axis=0)
    j +=1 

In [68]:
(unique, counts) = np.unique(pred, return_counts=True)
print(unique, counts)

[0. 1.] [   344 538460]


<br><br><br><br>
#   Applying Gaussian Naive bayes Classifier

In [24]:
from sklearn.naive_bayes import GaussianNB
gaus_clf = GaussianNB()
gaus_clf.fit(X_train, y_train)

y_pred_glb = gaus_clf.predict(X_test)
confusion = metrics.confusion_matrix(y_test, y_pred_glb)
print(confusion)
print(metrics.classification_report(y_test, y_pred_glb))

[[  1501  17411]
 [ 13025 506867]]
              precision    recall  f1-score   support

         0.0       0.10      0.08      0.09     18912
         1.0       0.97      0.97      0.97    519892

    accuracy                           0.94    538804
   macro avg       0.54      0.53      0.53    538804
weighted avg       0.94      0.94      0.94    538804



<br><br><br><br>
# Applying naive bayes algorithm

In [26]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler

pipe  = Pipeline([("mn",MinMaxScaler()),("nb",GaussianNB())])
pipe.fit(X_train,y_train)

# do this again
y_prednb = pipe.predict(X_test)
print(y_test)
print(y_prednb)
print(accuracy_score(y_test,y_prednb))

confusion = metrics.confusion_matrix(y_test, y_prednb)
print(confusion)
print(metrics.classification_report(y_test, y_prednb))

1285464    1.0
2646597    1.0
1279586    1.0
1426548    1.0
76436      1.0
          ... 
951187     1.0
1902794    1.0
2525449    1.0
1697574    1.0
2349247    1.0
Name: CASE_STATUS, Length: 538804, dtype: float64
[1. 1. 1. ... 1. 1. 1.]
0.9435119264148002
[[  1501  17411]
 [ 13025 506867]]
              precision    recall  f1-score   support

         0.0       0.10      0.08      0.09     18912
         1.0       0.97      0.97      0.97    519892

    accuracy                           0.94    538804
   macro avg       0.54      0.53      0.53    538804
weighted avg       0.94      0.94      0.94    538804



# KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors = 3)
knn_clf.fit(X_train,y_train)
knn_clf.score(X_test,y_test)



y_predknn = pipe.predict(X_test)
print(y_test)
print(y_predknn)
print(accuracy_score(y_test,y_predknn))

confusion = metrics.confusion_matrix(y_test, y_predknn)
print(confusion)
print(metrics.classification_report(y_test, y_predknn))

# Gradint Boosting Classifier

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
gb_clf = GradientBoostingClassifier()
gb_clf.fit(X_train,y_train)
gb_clf.score(X_test,y_test)



y_predgb = pipe.predict(X_test)
print(y_test)
print(y_predgb)
print(accuracy_score(y_test,y_pred))

confusion = metrics.confusion_matrix(y_test, y_predgb)
print(confusion)
print(metrics.classification_report(y_test, y_predgb))

# Tuning Gradiant Boosting Classifier

In [ ]:
gb_clf_ = GradientBoostingClassifier(n_estimators = 40)
gb_clf_.fit(X_train,y_train)
gb_clf_.score(X_test,y_test)



y_predgbc = pipe.predict(X_test)
print(y_test)
print(y_predgbc)
print(accuracy_score(y_test,y_predgbc))

confusion = metrics.confusion_matrix(y_test, y_predgbc)
print(confusion)
print(metrics.classification_report(y_test, y_predgbc))

# Support Vector Machine(SVM)

In [ ]:
from sklearn.svm import SVC

sv_clf = SVC(probability=True,kernel='linear')
sv_clf.fit(X_train,y_train)
sv_clf.fit(X_test)



y_predsvm = pipe.predict(X_test)
print(y_test)
print(y_predsvm)
print(accuracy_score(y_test,y_predsvm))

confusion = metrics.confusion_matrix(y_test, y_predsvm)
print(confusion)
print(metrics.classification_report(y_test, y_predsvm))